feat added footer designs (desktop)
tanmoy27112000/flutter_web_base pull request #12
Opened 2024-01-20 14:11 UTC by YuvrajSingh3110

solves issue #2

2024-01-22 15:17 UTC, tanmoy27112000 commented
@YuvrajSingh3110 please attach screen recording

2024-01-22 15:27 UTC, tanmoy27112000 requested changes

2024-01-22 15:27 UTC, tanmoy27112000 commented on example/lib/screen/footer_page.dart
> +import 'package:flutter_web_base/footer/footer_5/footer_5.dart';
this should not be imported directly it should be added in the `footer.dart` file in the `footer` folder

2024-01-23 09:44 UTC, YuvrajSingh3110 commented
https://github.com/tanmoy27112000/flutter_web_base/assets/96365625/36190aa5-06de-44c1-8b68-9bde4818974c

2024-01-23 13:41 UTC, tanmoy27112000 approved these changes

2024-01-23 13:42 UTC, merged